uploads = []

[[generated]]
id = "Hnr-0TPCDjVIsnwSKvPYQ"
uri = "file://artifacts/jupeb-prep/public/logo.png"
type = "image"
title = "jupeb prep logo star J"

[[generated]]
id = "isVV4R2EqZoNQWjtVFhB4"
uri = "file://artifacts/jupeb-prep/public/favicon-gen.png"
type = "image"
title = "jupeb favicon icon J star"

[[generated]]
id = "wu90nskE9OXc4OKQM-LAR"
uri = "file://attached_assets/generated_images/app_icon_for_jupeb_e5a5.png"
type = "image"
title = "generated_image"

[[generated]]
id = "3CcoWNTrSjwGKtxP5pKwX"
uri = "file://attached_assets/generated_images/app_icon_for_a_7588.png"
type = "image"
title = "generated_image"

[[outputs]]
id = "fdCmVTgZLnTn3qT8o00TO"
uri = "file://README.md"
type = "text"
title = "JUPEB Prep — README"
