import { Router, type IRouter } from "express";
import healthRouter from "./health";
import authRouter from "./auth";
import subjectsRouter from "./subjects";
import questionsRouter from "./questions";
import questionsBulkRouter from "./questions-bulk";
import notesRouter from "./notes";
import quizRouter from "./quiz";
import dashboardRouter from "./dashboard";
import aiRouter from "./ai";
import communityRouter from "./community";
import announcementsRouter from "./announcements";
import settingsRouter from "./settings";
import adminRouter from "./admin";
import leaderboardRouter from "./leaderboard";
import ttsRouter from "./tts";
import paymentRouter from "./payment";
import whatsappRouter from "./whatsapp";
import yarngptRouter from "./yarngpt";

const router: IRouter = Router();

router.use(healthRouter);
router.use(authRouter);
router.use(subjectsRouter);
router.use(questionsBulkRouter);
router.use(questionsRouter);
router.use(notesRouter);
router.use(quizRouter);
router.use(dashboardRouter);
router.use(aiRouter);
router.use(communityRouter);
router.use(announcementsRouter);
router.use(settingsRouter);
router.use(adminRouter);
router.use(leaderboardRouter);
router.use(ttsRouter);
router.use(paymentRouter);
router.use(whatsappRouter);
router.use(yarngptRouter);

export default router;
